### ISSUE TITLE
install error in CentOS Linux

### ISSUE THREAD

**Issue by OUCyf** [ziyixi/pyfk#4]
Hi ziyi ! 

I am Yin Fu from USTC, I have been using your pyfk-code, so great work! It worked fine when I installed it on the Mac, but the following error occurred when I installed it on the server? I used anaconda with python3.8.5 in Centos. Whether this is a bug?

```
In file included from /data/yinf/1.Software/pyfk-master/pyfk/gf/waveform_integration.c:642:0:
/home/yinf/anaconda3/lib/python3.8/site-packages/cysignals/struct_signals.h:45:26: 错误：expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘int’
 typedef volatile _Atomic int cy_atomic_int;
                          ^
/home/yinf/anaconda3/lib/python3.8/site-packages/cysignals/struct_signals.h:60:5: 错误：未知的类型名‘cy_atomic_int’
     cy_atomic_int sig_on_count;
     ^
/home/yinf/anaconda3/lib/python3.8/site-packages/cysignals/struct_signals.h:68:5: 错误：未知的类型名‘cy_atomic_int’
     cy_atomic_int interrupt_received;
     ^
/home/yinf/anaconda3/lib/python3.8/site-packages/cysignals/struct_signals.h:74:5: 错误：未知的类型名‘cy_atomic_int’
     cy_atomic_int inside_signal_handler;
     ^
/home/yinf/anaconda3/lib/python3.8/site-packages/cysignals/struct_signals.h:79:5: 错误：未知的类型名‘cy_atomic_int’
     cy_atomic_int block_sigint;
     ^
/data/yinf/1.Software/pyfk-master/pyfk/gf/waveform_integration.c: 在函数‘__pyx_f_4pyfk_2gf_20waveform_integration_kernel’中:
/data/yinf/1.Software/pyfk-master/pyfk/gf/waveform_integration.c:5959:35: 警告 在有符号和无符号整数表达式间比较 [-Wsign-compare]
     __pyx_t_11 = ((__pyx_v_ilayer == (__pyx_t_10 - 1)) != 0);
                                   ^
error: command 'gcc' failed with exit status 1
(base) [yinf@localhost pyfk-master]$ 
```

**Comment by ziyixi** [comment]
Hi Yin,

Thanks for pointing out the problem! Nice to see an alumnus here. It seems the unknown type name `cy_atomic_int` is due to the first error. I search in Google and find this question https://stackoverflow.com/questions/41499380/trouble-compiling-c-code-error-expected-asm-or-attribute/41500103

In the second answer, it seems the problem is related to the compiler version. Which version of the gcc are you using? And also the package cysignals have been updated recently. While I am still using the old version, I don't know if the new version of this package brings some new bugs there. 

I am a little bit busy working on other things these days and will get my package updated laterwards.
