### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by HappyZooo** [ziyixi/pyfk#9]
Hello, when USING conda installation according to your instructions, the following error keeps showing, how to solve it?

C:\Users\Dell>conda install --channel https://conda.anaconda.org/ziyixi pyfk
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyfk

Current channels:

  - https://conda.anaconda.org/ziyixi/win-64
  - https://conda.anaconda.org/ziyixi/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by ziyixi** [comment]
Hello,

Can you try `conda install -c ziyixi pyfk` as shown in [the anaconda cloud](https://anaconda.org/ziyixi/pyfk). I have tested your command, and it seems not working. After `--channel`, I am afraid that it should just be a simple name but not the URL.

**Comment by HappyZooo** [comment]
Thanks for your reply.


&nbsp; &nbsp; &nbsp; I have solved the installation problem. But there are still some things I don't understand.


&nbsp; &nbsp; &nbsp;1. I have noticed that at smaller epicentral distances, or in your example "PREM" in the tutorial file, P and S waves are very close to each other. After the plot is drawn, the P and S waves overlap. But when I test the epicenter distance is relatively large, the P wave and S wave waveform is easy to distinguish. How can this be avoided when using smaller epicentral distances?





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ZiYi ***@***.***&gt;; 
发送时间: 2022年3月22日(星期二) 晚上10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ziyixi/pyfk] Installation error (Issue #9)





 
Hello,
 
Can you try conda install -c ziyixi pyfk as shown in the anaconda cloud. I have tested your command, and it seems not working. After --channel, I am afraid that it should just be a simple name but not the URL.

**Comment by ziyixi** [comment]
Hello,

I think this is expected for the test model. As the model is very coarse, it may not be able to get distinguishable P and S for a small epicenter distance. I suggest using higher frequency stimulation and a more accurate PREM model (maybe directly do interpolation from the original model?)to get better phases for P and S.

**Comment by HappyZooo** [comment]
Thanks again for your reply.


&nbsp; &nbsp; &nbsp; I tested the source at a depth of 5km with&nbsp;&nbsp;receive distance&nbsp;of 3km, 6km and 9km. 1D velocity model with 5 layers.


&nbsp; &nbsp; &nbsp;This time, I have attached my waveform test results (in the case of 3km, the first arrival time of P wave is 1.06s, and the first arrival time of S wave is 1.84s).


1. When (NPT =512, DT =0.01), FIG. 1 shows the waveform of GF, and FIG. 2 shows the synthetic waveform.


2. When (NPT =512, DT =0.1),&nbsp; &nbsp;FIG. 3 shows the waveform of GF, and FIG. 4 shows the synthetic waveform.


3. When (NPT =4096, DT =0.001), Fig.5 shows the waveform of GF.


&nbsp; &nbsp; &nbsp;The difference can be clearly seen on the GF image. But why it's hard to tell apart after the composite image. Can it be understood that the drawing accuracy is not enough when using ''calculate_sync''? Or can I separate P and S waves in GF, so as to synthesize the composite image of P-band and S-band respectively?


&nbsp; &nbsp; &nbsp;Finally, I noticed that when using the 1D velocity model, the changes of Qs and Qp seem to have no effect on the arrival time of P and S waves. I wonder if it is a bug.



&nbsp;&nbsp;
&nbsp; &nbsp; &nbsp;Thanks again for your reply in spite of your busy schedule.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ziyixi/pyfk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月2日(星期六) 晚上11:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ziyixi/pyfk] Installation error (Issue #9)





 
Hello,
 
I think this is expected for the test model. As the model is very coarse, it may not be able to get distinguishable P and S for a small epicenter distance. I suggest using higher frequency stimulation and a more accurate PREM model (maybe directly do interpolation from the original model?)to get better phases for P and S.

**Comment by ziyixi** [comment]
Hello,

Sorry for the late reply, it's really a busy week for me. I couldn't see your figures both on GitHub and in the email. Maybe you can attach it to the GitHub issue page instead?

And I have the following thoughts based on your description:
1. You mentioned that P and S could not be distinguished. I am wondering what epicenter distance you are using? For small distances, the P and S might be very close and hard to tell apart. But you can see them in the Green function, so the only problem might be in the convolution part, from the Green function to the actual waveform. Then I suppose that might be the issue related to the source time function. The length of the source will also influence the waveform. So when the source time is larger than the P and S time difference, I guess it will be hard to tell them apart. I don't think it is a bug here as it's natural to have several seconds of the source time. Maybe you can try larger epicenter distance?
2. You also mentioned that attenuation seems to have no effect on the waveform. Frankly speaking, I have not done many tests about that. The way I am developing the package is to mimic the behavior of the original FK package which has been widely tested by users. I generate several test examples (as you can see in the pyfk/tests directory) and compare the result between this package with FK, and they behave exactly the same. But you are right that more tests are needed for the attenuation. At the moment I have not found the bug related to that part. I am not studying attenuation, but I have heard a lot that attenuation influences the amplitude the most, with a slight influence on the phase shape. So maybe that is the reason here?
